global:
  resolve_timeout: 5m

route:
  receiver: default-receiver

receivers:
  - name: default-receiver
    slack_configs:
      - api_url: # slack webhook url 입력필요
        channel: '#monitoring'
        send_resolved: true
